import Icon from "@/components/Icon";

const kpis = [
  { label: "Revenue", value: "$1.24M", note: "+8.3% MoM", up: true },
  { label: "Gross Margin", value: "42.6%", note: "+1.2 pts", up: true },
  { label: "EBITDA", value: "$312K", note: "+11% MoM", up: true },
  { label: "Net Income", value: "$198K", note: "+6.4% MoM", up: true },
];

const pl = [
  ["Revenue", "1,240,000"],
  ["Cost of Goods Sold", "(712,000)"],
  ["Gross Profit", "528,000"],
  ["Operating Expenses", "(216,000)"],
  ["EBITDA", "312,000"],
  ["Net Income", "198,000"],
];

const pages = ["Cover", "Executive Summary", "P&L", "Balance Sheet", "Cash Flow", "KPIs", "Risk Register", "Outlook"];

export default function ExampleReport() {
  return (
    <div className="mx-auto max-w-3xl overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-soft">
      {/* document header */}
      <div className="flex items-center justify-between gap-3 border-b border-slate-100 bg-slate-50 px-6 py-4">
        <div>
          <p className="text-[11px] font-semibold uppercase tracking-wider text-brand-600">CFO Board Pack</p>
          <h3 className="font-display text-lg font-bold text-charcoal">Northwind Trading - March 2026</h3>
        </div>
        <span className="hidden shrink-0 items-center gap-1.5 rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-600 sm:inline-flex">
          <span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />
          Auto-generated
        </span>
      </div>

      <div className="p-6">
        {/* KPI row */}
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
          {kpis.map((k) => (
            <div key={k.label} className="rounded-xl border border-slate-200/70 bg-white p-3 shadow-card">
              <p className="text-[11px] font-medium text-slate-500">{k.label}</p>
              <p className="mt-1 font-display text-xl font-extrabold text-charcoal">{k.value}</p>
              <p className="mt-0.5 flex items-center gap-1 text-[11px] font-semibold text-emerald-600">
                <Icon name="trending" className="h-3 w-3" />
                {k.note}
              </p>
            </div>
          ))}
        </div>

        {/* executive summary */}
        <div className="mt-6">
          <p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Executive Summary</p>
          <p className="mt-2 text-sm leading-relaxed text-slate-600">
            This month the company recorded total revenue of $1.24M, up 8.3% month over month, with a
            gross margin of 42.6%. EBITDA closed at $312K and net income at $198K, supported by
            disciplined cost control and stronger receivable collections. Cash runway remains healthy
            at 14 months.
          </p>
        </div>

        {/* P&L table */}
        <div className="mt-6">
          <p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Profit &amp; Loss Overview</p>
          <div className="mt-3 overflow-hidden rounded-xl border border-slate-200/70">
            {pl.map((row, i) => (
              <div
                key={row[0]}
                className={`flex items-center justify-between px-4 py-2.5 text-sm ${
                  i % 2 ? "bg-slate-50/60" : "bg-white"
                } ${["Gross Profit", "EBITDA", "Net Income"].includes(row[0]) ? "font-bold text-charcoal" : "text-slate-600"}`}
              >
                <span>{row[0]}</span>
                <span className="tabular-nums">{row[1]}</span>
              </div>
            ))}
          </div>
        </div>

        {/* pages included */}
        <div className="mt-6">
          <p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Pages in this pack</p>
          <div className="mt-3 flex flex-wrap gap-2">
            {pages.map((p) => (
              <span key={p} className="inline-flex items-center gap-1.5 rounded-full border border-slate-200 bg-white px-3 py-1 text-xs font-medium text-slate-600">
                <Icon name="doc" className="h-3.5 w-3.5 text-brand-500" />
                {p}
              </span>
            ))}
          </div>
        </div>
      </div>

      <div className="border-t border-slate-100 bg-slate-50 px-6 py-3 text-center text-[11px] text-slate-400">
        Auto-generated by InfiBooks - Confidential, for board review only
      </div>
    </div>
  );
}
